// Elenco jogável. Cada herói tem atributos base, uma habilidade suprema
// (gasta 100 de fé acumulada em combate) e uma passiva com gatilho.
(function (global) {
  const Jogo = (global.Jogo = global.Jogo || {});

  const HEROIS = [
    // ---------------------------------------------------------- PATRIARCAS
    {
      id: "moises",
      nome: "Moisés",
      titulo: "O Libertador",
      faccao: "patriarcas",
      classe: "vidente",
      raridade: "lendario",
      versiculo: "Êxodo 14:21",
      arte: { tunica: "#e8e2d2", manto: "#7d5ba6", pele: "#c98d5e", cabelo: "#d8d8d8", simbolo: "cajado" },
      base: { vida: 1180, atk: 172, def: 58, spd: 106, crit: 0.18, critDano: 1.8 },
      ult: {
        nome: "Mar Vermelho",
        desc: "As águas se abrem e desabam: dano em todos os inimigos e atordoamento na linha de trás.",
        acoes: [
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.35 },
          { tipo: "atordoar", alvo: "inimigos_tras", chance: 0.7, duracao: 1 },
        ],
      },
      passiva: {
        nome: "Vara de Deus",
        desc: "No início da batalha reduz a defesa de todos os inimigos em 20% por 3 turnos.",
        gatilho: "inicio",
        acoes: [{ tipo: "mod", alvo: "todos_inimigos", stat: "def", valor: -0.2, duracao: 3, nome: "Praga" }],
      },
    },
    {
      id: "abraao",
      nome: "Abraão",
      titulo: "Pai da Fé",
      faccao: "patriarcas",
      classe: "arauto",
      raridade: "lendario",
      versiculo: "Gênesis 15:5",
      arte: { tunica: "#d9c9a3", manto: "#8a6a3f", pele: "#c98d5e", cabelo: "#e6e6e6", simbolo: "estrela" },
      base: { vida: 1260, atk: 132, def: 66, spd: 112, crit: 0.16, critDano: 1.7 },
      ult: {
        nome: "Promessa das Estrelas",
        desc: "Aumenta o ataque de toda a hoste em 35% e o crítico em 15% por 3 turnos.",
        acoes: [
          { tipo: "mod", alvo: "todos_aliados", stat: "atk", valor: 0.35, duracao: 3, nome: "Promessa" },
          { tipo: "mod", alvo: "todos_aliados", stat: "crit", valor: 0.15, duracao: 3, nome: "Promessa" },
        ],
      },
      passiva: {
        nome: "Aliança Eterna",
        desc: "Ao entrar em combate concede um escudo a todos os aliados.",
        gatilho: "inicio",
        acoes: [{ tipo: "escudo", alvo: "todos_aliados", mult: 1.1 }],
      },
    },
    {
      id: "noe",
      nome: "Noé",
      titulo: "O Justo do Dilúvio",
      faccao: "patriarcas",
      classe: "sacerdote",
      raridade: "epico",
      versiculo: "Gênesis 6:14",
      arte: { tunica: "#cdb894", manto: "#4f7a6a", pele: "#c98d5e", cabelo: "#dcdcdc", simbolo: "jarro" },
      base: { vida: 1320, atk: 118, def: 68, spd: 108, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "A Arca",
        desc: "Abriga os aliados: cura todos e protege com escudo por 2 turnos.",
        acoes: [
          { tipo: "cura", alvo: "todos_aliados", mult: 1.0 },
          { tipo: "escudo", alvo: "todos_aliados", mult: 0.9 },
        ],
      },
      passiva: {
        nome: "Sinal do Arco-Íris",
        desc: "Quando um aliado cai abaixo de 40% de vida, recebe cura imediata.",
        gatilho: "aliado_ferido",
        acoes: [{ tipo: "cura", alvo: "aliado_menor_vida", mult: 0.75 }],
      },
    },
    {
      id: "jose",
      nome: "José",
      titulo: "O Intérprete de Sonhos",
      faccao: "patriarcas",
      classe: "arauto",
      raridade: "epico",
      versiculo: "Gênesis 41:16",
      arte: { tunica: "#e5d9b0", manto: "#c2544d", pele: "#c98d5e", cabelo: "#3b2b1e", simbolo: "pergaminho" },
      base: { vida: 1180, atk: 128, def: 60, spd: 118, crit: 0.18, critDano: 1.7 },
      ult: {
        nome: "Sonhos do Faraó",
        desc: "Prevê o ataque inimigo: acelera os aliados e devolve fé à hoste.",
        acoes: [
          { tipo: "mod", alvo: "todos_aliados", stat: "spd", valor: 0.25, duracao: 3, nome: "Visão" },
          { tipo: "energia", alvo: "todos_aliados", valor: 25 },
        ],
      },
      passiva: {
        nome: "Túnica Colorida",
        desc: "Começa o combate com 30 de fé acumulada.",
        gatilho: "inicio",
        acoes: [{ tipo: "energia", alvo: "self", valor: 30 }],
      },
    },
    {
      id: "jaco",
      nome: "Jacó",
      titulo: "Aquele que Lutou",
      faccao: "patriarcas",
      classe: "guerreiro",
      raridade: "raro",
      versiculo: "Gênesis 32:28",
      arte: { tunica: "#b89a6a", manto: "#6b4f2a", pele: "#c98d5e", cabelo: "#4a3620", simbolo: "escudo" },
      base: { vida: 1720, atk: 104, def: 86, spd: 96, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "Luta com o Anjo",
        desc: "Agarra o inimigo e rouba vida com o golpe.",
        acoes: [{ tipo: "roubo", alvo: "alvo", mult: 1.9, roubo: 0.6 }],
      },
      passiva: {
        nome: "Coxa Ferida",
        desc: "Abaixo de 45% de vida ganha 30% de defesa permanente.",
        gatilho: "vida_baixa",
        acoes: [{ tipo: "mod", alvo: "self", stat: "def", valor: 0.3, duracao: 99, nome: "Cicatriz" }],
      },
    },
    {
      id: "isaque",
      nome: "Isaque",
      titulo: "O Filho da Promessa",
      faccao: "patriarcas",
      classe: "sacerdote",
      raridade: "raro",
      versiculo: "Gênesis 22:8",
      arte: { tunica: "#ded3b6", manto: "#8fb5a0", pele: "#c98d5e", cabelo: "#5a4326", simbolo: "chama" },
      base: { vida: 1240, atk: 114, def: 62, spd: 110, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "Cordeiro no Espinheiro",
        desc: "Cura profundamente o aliado mais ferido e o protege.",
        acoes: [
          { tipo: "cura", alvo: "aliado_menor_vida", mult: 2.1 },
          { tipo: "escudo", alvo: "aliado_menor_vida", mult: 0.8 },
        ],
      },
      passiva: {
        nome: "Bênção do Campo",
        desc: "A cada turno regenera vida da hoste.",
        gatilho: "cada_turno",
        acoes: [{ tipo: "cura", alvo: "todos_aliados", mult: 0.22 }],
      },
    },

    // -------------------------------------------------------------- JUÍZES
    {
      id: "sansao",
      nome: "Sansão",
      titulo: "A Força do Nazireu",
      faccao: "juizes",
      classe: "guerreiro",
      raridade: "lendario",
      versiculo: "Juízes 16:30",
      arte: { tunica: "#9c6b3f", manto: "#c2544d", pele: "#b87a4a", cabelo: "#2b1d12", simbolo: "coluna" },
      base: { vida: 1880, atk: 128, def: 88, spd: 98, crit: 0.16, critDano: 1.9 },
      ult: {
        nome: "Pilares de Dagom",
        desc: "Derruba o templo: dano brutal em todos, ao custo de 12% da própria vida.",
        acoes: [
          { tipo: "sacrificio", alvo: "self", pct: 0.12 },
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.55 },
        ],
      },
      passiva: {
        nome: "Sete Tranças",
        desc: "Quanto menor a vida, maior o ataque (até +60%).",
        gatilho: "cada_turno",
        acoes: [{ tipo: "furia", alvo: "self", max: 0.6 }],
      },
    },
    {
      id: "josue",
      nome: "Josué",
      titulo: "O Conquistador",
      faccao: "juizes",
      classe: "guerreiro",
      raridade: "lendario",
      versiculo: "Josué 6:20",
      arte: { tunica: "#a8a29a", manto: "#c9a227", pele: "#c98d5e", cabelo: "#2f2318", simbolo: "espada" },
      base: { vida: 1800, atk: 124, def: 92, spd: 100, crit: 0.14, critDano: 1.7 },
      ult: {
        nome: "Muralhas de Jericó",
        desc: "As trombetas ressoam: dano em área e defesa inimiga despedaçada.",
        acoes: [
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.1 },
          { tipo: "mod", alvo: "todos_inimigos", stat: "def", valor: -0.35, duracao: 3, nome: "Ruína" },
        ],
      },
      passiva: {
        nome: "Sol Parado",
        desc: "Provoca os inimigos por 2 turnos ao entrar em combate.",
        gatilho: "inicio",
        acoes: [{ tipo: "provocar", alvo: "todos_inimigos", duracao: 2 }],
      },
    },
    {
      id: "debora",
      nome: "Débora",
      titulo: "A Juíza sob a Palmeira",
      faccao: "juizes",
      classe: "arauto",
      raridade: "epico",
      versiculo: "Juízes 5:12",
      arte: { tunica: "#e0c060", manto: "#8f4f9c", pele: "#b87a4a", cabelo: "#241a12", simbolo: "harpa" },
      base: { vida: 1220, atk: 130, def: 62, spd: 120, crit: 0.18, critDano: 1.7 },
      ult: {
        nome: "Cântico da Vitória",
        desc: "O cântico acelera a hoste e afia seus golpes.",
        acoes: [
          { tipo: "mod", alvo: "todos_aliados", stat: "spd", valor: 0.3, duracao: 3, nome: "Cântico" },
          { tipo: "mod", alvo: "todos_aliados", stat: "crit", valor: 0.2, duracao: 3, nome: "Cântico" },
        ],
      },
      passiva: {
        nome: "Palavra de Comando",
        desc: "Sempre que ataca, devolve 10 de fé ao aliado mais lento.",
        gatilho: "ao_atacar",
        acoes: [{ tipo: "energia", alvo: "aliado_menor_energia", valor: 10 }],
      },
    },
    {
      id: "gideao",
      nome: "Gideão",
      titulo: "Os Trezentos",
      faccao: "juizes",
      classe: "arqueiro",
      raridade: "epico",
      versiculo: "Juízes 7:20",
      arte: { tunica: "#c3a36b", manto: "#3f6b8a", pele: "#c98d5e", cabelo: "#3a2a1a", simbolo: "tocha" },
      base: { vida: 1040, atk: 168, def: 50, spd: 122, crit: 0.3, critDano: 1.85 },
      ult: {
        nome: "Tochas e Trombetas",
        desc: "Quatro investidas relâmpago em alvos aleatórios.",
        acoes: [{ tipo: "dano", alvo: "aleatorio_inimigos:4", mult: 0.72 }],
      },
      passiva: {
        nome: "Velo de Lã",
        desc: "O primeiro golpe recebido em cada batalha é anulado.",
        gatilho: "inicio",
        acoes: [{ tipo: "imune", alvo: "self", duracao: 1 }],
      },
    },
    {
      id: "jefte",
      nome: "Jefté",
      titulo: "O Voto de Gileade",
      faccao: "juizes",
      classe: "guerreiro",
      raridade: "raro",
      versiculo: "Juízes 11:30",
      arte: { tunica: "#8a7a5a", manto: "#7a3f3f", pele: "#b87a4a", cabelo: "#241a12", simbolo: "machado" },
      base: { vida: 1680, atk: 112, def: 80, spd: 100, crit: 0.14, critDano: 1.75 },
      ult: {
        nome: "Voto de Sangue",
        desc: "Golpe pesado que sangra o inimigo por 3 turnos.",
        acoes: [
          { tipo: "dano", alvo: "alvo", mult: 1.7 },
          { tipo: "dot", alvo: "alvo", estilo: "sangramento", mult: 0.3, duracao: 3 },
        ],
      },
      passiva: {
        nome: "Exilado",
        desc: "Ganha 15% de ataque a cada aliado caído.",
        gatilho: "aliado_caiu",
        acoes: [{ tipo: "mod", alvo: "self", stat: "atk", valor: 0.15, duracao: 99, nome: "Ira" }],
      },
    },
    {
      id: "baraque",
      nome: "Baraque",
      titulo: "Capitão de Israel",
      faccao: "juizes",
      classe: "arqueiro",
      raridade: "raro",
      versiculo: "Juízes 4:14",
      arte: { tunica: "#9aa88a", manto: "#5a6b3f", pele: "#c98d5e", cabelo: "#2f2318", simbolo: "arco" },
      base: { vida: 1000, atk: 158, def: 48, spd: 118, crit: 0.26, critDano: 1.8 },
      ult: {
        nome: "Flecha do Monte Tabor",
        desc: "Dispara contra o inimigo mais ferido, com dano extra se ele estiver fraco.",
        acoes: [{ tipo: "executar", alvo: "inimigo_menor_vida", mult: 1.8, limiar: 0.4, bonus: 1.7 }],
      },
      passiva: {
        nome: "Ao Lado da Profetisa",
        desc: "Recebe 20% de ataque enquanto houver um Arauto vivo na hoste.",
        gatilho: "inicio",
        acoes: [{ tipo: "mod_condicional", alvo: "self", stat: "atk", valor: 0.2, requerClasse: "arauto", duracao: 99, nome: "Aliança" }],
      },
    },

    // ------------------------------------------------------------ PROFETAS
    {
      id: "elias",
      nome: "Elias",
      titulo: "O Fogo do Carmelo",
      faccao: "profetas",
      classe: "vidente",
      raridade: "lendario",
      versiculo: "1 Reis 18:38",
      arte: { tunica: "#7a4a2a", manto: "#e07a2a", pele: "#b87a4a", cabelo: "#d8d8d8", simbolo: "chama" },
      base: { vida: 1120, atk: 182, def: 52, spd: 110, crit: 0.22, critDano: 1.9 },
      ult: {
        nome: "Fogo do Céu",
        desc: "Chama devoradora sobre um alvo, deixando queimadura por 3 turnos.",
        acoes: [
          { tipo: "dano", alvo: "inimigo_maior_atk", mult: 2.6 },
          { tipo: "dot", alvo: "inimigo_maior_atk", estilo: "queimadura", mult: 0.42, duracao: 3 },
        ],
      },
      passiva: {
        nome: "Carro de Fogo",
        desc: "Ao derrotar um inimigo, recupera 25 de fé.",
        gatilho: "ao_matar",
        acoes: [{ tipo: "energia", alvo: "self", valor: 25 }],
      },
    },
    {
      id: "eliseu",
      nome: "Eliseu",
      titulo: "Herdeiro do Manto",
      faccao: "profetas",
      classe: "sacerdote",
      raridade: "epico",
      versiculo: "2 Reis 2:9",
      arte: { tunica: "#d4c8a8", manto: "#4a6b8a", pele: "#c98d5e", cabelo: "#8a8a8a", simbolo: "manto" },
      base: { vida: 1300, atk: 122, def: 66, spd: 112, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "Porção Dobrada",
        desc: "Ressuscita um aliado caído com 45% da vida; se não houver, cura toda a hoste.",
        acoes: [
          { tipo: "reviver", alvo: "aliado_caido", pct: 0.45 },
          { tipo: "cura", alvo: "todos_aliados", mult: 0.85 },
        ],
      },
      passiva: {
        nome: "Azeite que não Falta",
        desc: "As curas que realiza são 25% mais fortes.",
        gatilho: "passivo",
        acoes: [{ tipo: "amplifica_cura", valor: 0.25 }],
      },
    },
    {
      id: "daniel",
      nome: "Daniel",
      titulo: "A Cova dos Leões",
      faccao: "profetas",
      classe: "sacerdote",
      raridade: "epico",
      versiculo: "Daniel 6:22",
      arte: { tunica: "#e2dcc0", manto: "#3f5f8a", pele: "#c98d5e", cabelo: "#2a2018", simbolo: "leao" },
      base: { vida: 1340, atk: 126, def: 70, spd: 106, crit: 0.14, critDano: 1.6 },
      ult: {
        nome: "Boca dos Leões Fechada",
        desc: "Torna a hoste imune a dano por 1 turno e limpa maldições.",
        acoes: [
          { tipo: "imune", alvo: "todos_aliados", duracao: 1 },
          { tipo: "purificar", alvo: "todos_aliados" },
        ],
      },
      passiva: {
        nome: "Oração de Joelhos",
        desc: "A cada turno recupera 8 de fé para si e para o aliado mais ferido.",
        gatilho: "cada_turno",
        acoes: [
          { tipo: "energia", alvo: "self", valor: 8 },
          { tipo: "energia", alvo: "aliado_menor_vida", valor: 8 },
        ],
      },
    },
    {
      id: "ezequiel",
      nome: "Ezequiel",
      titulo: "O Vale dos Ossos",
      faccao: "profetas",
      classe: "vidente",
      raridade: "epico",
      versiculo: "Ezequiel 37:5",
      arte: { tunica: "#b8b0a0", manto: "#5f5f7a", pele: "#c98d5e", cabelo: "#3a3028", simbolo: "olho" },
      base: { vida: 1120, atk: 166, def: 54, spd: 104, crit: 0.2, critDano: 1.8 },
      ult: {
        nome: "Ossos Secos",
        desc: "Dano espectral em área que regenera a hoste com a energia drenada.",
        acoes: [
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.05 },
          { tipo: "regen", alvo: "todos_aliados", mult: 0.28, duracao: 3 },
        ],
      },
      passiva: {
        nome: "Rodas dentro de Rodas",
        desc: "Inimigos atingidos por sua suprema perdem 15 de fé.",
        gatilho: "ao_usar_ult",
        acoes: [{ tipo: "energia", alvo: "todos_inimigos", valor: -15 }],
      },
    },
    {
      id: "isaias",
      nome: "Isaías",
      titulo: "Lábios de Brasa",
      faccao: "profetas",
      classe: "vidente",
      raridade: "raro",
      versiculo: "Isaías 6:6",
      arte: { tunica: "#ddd0b0", manto: "#a83f3f", pele: "#c98d5e", cabelo: "#6a5a48", simbolo: "brasa" },
      base: { vida: 1060, atk: 158, def: 50, spd: 108, crit: 0.2, critDano: 1.75 },
      ult: {
        nome: "Brasa do Altar",
        desc: "Queima a linha de frente inimiga e purifica os aliados.",
        acoes: [
          { tipo: "dano", alvo: "inimigos_frente", mult: 1.5 },
          { tipo: "purificar", alvo: "todos_aliados" },
        ],
      },
      passiva: {
        nome: "Eis-me Aqui",
        desc: "Começa a batalha com 20 de fé.",
        gatilho: "inicio",
        acoes: [{ tipo: "energia", alvo: "self", valor: 20 }],
      },
    },
    {
      id: "jeremias",
      nome: "Jeremias",
      titulo: "O Profeta das Lágrimas",
      faccao: "profetas",
      classe: "arauto",
      raridade: "raro",
      versiculo: "Jeremias 1:5",
      arte: { tunica: "#b0a894", manto: "#4a4a5a", pele: "#c98d5e", cabelo: "#4a3a2a", simbolo: "pergaminho" },
      base: { vida: 1180, atk: 124, def: 60, spd: 112, crit: 0.14, critDano: 1.6 },
      ult: {
        nome: "Lamentações",
        desc: "O pranto quebra o ânimo inimigo: -30% de ataque por 3 turnos.",
        acoes: [
          { tipo: "mod", alvo: "todos_inimigos", stat: "atk", valor: -0.3, duracao: 3, nome: "Lamento" },
          { tipo: "dano", alvo: "todos_inimigos", mult: 0.6 },
        ],
      },
      passiva: {
        nome: "Cisterna Vazia",
        desc: "Ao receber dano crítico, devolve 10 de fé a si mesmo.",
        gatilho: "ao_receber_dano",
        acoes: [{ tipo: "energia", alvo: "self", valor: 10 }],
      },
    },
    {
      id: "jonas",
      nome: "Jonas",
      titulo: "O Ventre do Peixe",
      faccao: "profetas",
      classe: "guerreiro",
      raridade: "comum",
      versiculo: "Jonas 2:1",
      arte: { tunica: "#7fa8a0", manto: "#3f5f5a", pele: "#c98d5e", cabelo: "#3a2a1a", simbolo: "peixe" },
      base: { vida: 1560, atk: 98, def: 76, spd: 94, crit: 0.1, critDano: 1.6 },
      ult: {
        nome: "Três Dias e Três Noites",
        desc: "Recupera 35% da vida máxima e sacode o inimigo à frente.",
        acoes: [
          { tipo: "cura", alvo: "self", mult: 0.0, pctVida: 0.35 },
          { tipo: "dano", alvo: "inimigo_frente", mult: 1.3 },
        ],
      },
      passiva: {
        nome: "Segunda Chance",
        desc: "Uma vez por batalha sobrevive a um golpe fatal com 20% de vida.",
        gatilho: "golpe_fatal",
        acoes: [{ tipo: "renascer", alvo: "self", pct: 0.2 }],
      },
    },
    {
      id: "joaobatista",
      nome: "João Batista",
      titulo: "A Voz no Deserto",
      faccao: "profetas",
      classe: "arauto",
      raridade: "epico",
      versiculo: "Mateus 3:3",
      arte: { tunica: "#8a7a5a", manto: "#6a5a3a", pele: "#b87a4a", cabelo: "#2a1d12", simbolo: "agua" },
      base: { vida: 1160, atk: 134, def: 58, spd: 124, crit: 0.18, critDano: 1.7 },
      ult: {
        nome: "Preparai o Caminho",
        desc: "Enche 50 de fé de dois aliados e os fortalece.",
        acoes: [
          { tipo: "energia", alvo: "aliados_menor_energia:2", valor: 50 },
          { tipo: "mod", alvo: "todos_aliados", stat: "atk", valor: 0.2, duracao: 2, nome: "Clamor" },
        ],
      },
      passiva: {
        nome: "Batismo",
        desc: "Limpa uma maldição de um aliado a cada turno.",
        gatilho: "cada_turno",
        acoes: [{ tipo: "purificar", alvo: "aliado_menor_vida", quantidade: 1 }],
      },
    },

    // ------------------------------------------------------------- REALEZA
    {
      id: "davi",
      nome: "Davi",
      titulo: "O Pastor Ungido",
      faccao: "realeza",
      classe: "arqueiro",
      raridade: "lendario",
      versiculo: "1 Samuel 17:45",
      arte: { tunica: "#d8b34a", manto: "#2f4f8f", pele: "#c98d5e", cabelo: "#8a5a2a", simbolo: "funda" },
      base: { vida: 1080, atk: 186, def: 52, spd: 124, crit: 0.32, critDano: 1.95 },
      ult: {
        nome: "Funda do Pastor",
        desc: "Uma pedra certeira e crítica contra o inimigo de maior ataque.",
        acoes: [{ tipo: "dano", alvo: "inimigo_maior_atk", mult: 2.5, criticoGarantido: true }],
      },
      passiva: {
        nome: "Coração Segundo Deus",
        desc: "Cada golpe crítico aumenta seu ataque em 8% (acumulável).",
        gatilho: "ao_critico",
        acoes: [{ tipo: "mod", alvo: "self", stat: "atk", valor: 0.08, duracao: 99, nome: "Unção" }],
      },
    },
    {
      id: "salomao",
      nome: "Salomão",
      titulo: "O Rei Sábio",
      faccao: "realeza",
      classe: "vidente",
      raridade: "lendario",
      versiculo: "1 Reis 3:12",
      arte: { tunica: "#f0d98a", manto: "#6a3f8a", pele: "#c98d5e", cabelo: "#2a2018", simbolo: "coroa" },
      base: { vida: 1200, atk: 176, def: 60, spd: 108, crit: 0.2, critDano: 1.85 },
      ult: {
        nome: "Juízo de Salomão",
        desc: "Corta em dois: dano em área e rouba 20% do ataque inimigo para a hoste.",
        acoes: [
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.2 },
          { tipo: "mod", alvo: "todos_inimigos", stat: "atk", valor: -0.2, duracao: 3, nome: "Juízo" },
          { tipo: "mod", alvo: "todos_aliados", stat: "atk", valor: 0.2, duracao: 3, nome: "Sabedoria" },
        ],
      },
      passiva: {
        nome: "Templo de Ouro",
        desc: "Concede 15% de defesa a toda a hoste no início da batalha.",
        gatilho: "inicio",
        acoes: [{ tipo: "mod", alvo: "todos_aliados", stat: "def", valor: 0.15, duracao: 99, nome: "Templo" }],
      },
    },
    {
      id: "ester",
      nome: "Ester",
      titulo: "A Rainha Intercessora",
      faccao: "realeza",
      classe: "arauto",
      raridade: "epico",
      versiculo: "Ester 4:16",
      arte: { tunica: "#e8a0c0", manto: "#8a2f5a", pele: "#d8a070", cabelo: "#2a1a12", simbolo: "coroa" },
      base: { vida: 1240, atk: 128, def: 64, spd: 120, crit: 0.18, critDano: 1.7 },
      ult: {
        nome: "Cetro de Ouro",
        desc: "Protege a hoste com escudo e encanta o inimigo mais forte, atordoando-o.",
        acoes: [
          { tipo: "escudo", alvo: "todos_aliados", mult: 0.85 },
          { tipo: "atordoar", alvo: "inimigo_maior_atk", chance: 0.85, duracao: 1 },
        ],
      },
      passiva: {
        nome: "Para Tal Tempo como Este",
        desc: "Quando um aliado cai, a hoste ganha 20% de velocidade por 2 turnos.",
        gatilho: "aliado_caiu",
        acoes: [{ tipo: "mod", alvo: "todos_aliados", stat: "spd", valor: 0.2, duracao: 2, nome: "Coragem" }],
      },
    },
    {
      id: "ezequias",
      nome: "Ezequias",
      titulo: "O Rei que Orou",
      faccao: "realeza",
      classe: "sacerdote",
      raridade: "raro",
      versiculo: "2 Reis 20:5",
      arte: { tunica: "#cfd8e8", manto: "#3f4f8a", pele: "#c98d5e", cabelo: "#3a2a1a", simbolo: "relogio" },
      base: { vida: 1280, atk: 116, def: 66, spd: 108, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "Sombra que Recua",
        desc: "Cura a hoste e devolve fé a todos.",
        acoes: [
          { tipo: "cura", alvo: "todos_aliados", mult: 0.95 },
          { tipo: "energia", alvo: "todos_aliados", valor: 15 },
        ],
      },
      passiva: {
        nome: "Quinze Anos a Mais",
        desc: "Cura 12% da vida do aliado que estiver abaixo de 30%.",
        gatilho: "aliado_ferido",
        acoes: [{ tipo: "cura", alvo: "aliado_menor_vida", mult: 0.5 }],
      },
    },
    {
      id: "josias",
      nome: "Josias",
      titulo: "O Rei Menino",
      faccao: "realeza",
      classe: "guerreiro",
      raridade: "raro",
      versiculo: "2 Reis 23:25",
      arte: { tunica: "#b8c8d8", manto: "#2f6b5a", pele: "#d8a070", cabelo: "#5a3a1a", simbolo: "espada" },
      base: { vida: 1700, atk: 108, def: 84, spd: 100, crit: 0.14, critDano: 1.65 },
      ult: {
        nome: "Reforma do Templo",
        desc: "Quebra ídolos: dano na frente inimiga e limpeza de maldições aliadas.",
        acoes: [
          { tipo: "dano", alvo: "inimigos_frente", mult: 1.45 },
          { tipo: "purificar", alvo: "todos_aliados" },
        ],
      },
      passiva: {
        nome: "Livro Encontrado",
        desc: "Ganha 20% de defesa após receber o primeiro golpe.",
        gatilho: "ao_receber_dano",
        acoes: [{ tipo: "mod", alvo: "self", stat: "def", valor: 0.2, duracao: 99, nome: "Zelo", unico: true }],
      },
    },
    {
      id: "rute",
      nome: "Rute",
      titulo: "A Fiel de Moabe",
      faccao: "realeza",
      classe: "sacerdote",
      raridade: "comum",
      versiculo: "Rute 1:16",
      arte: { tunica: "#d8c090", manto: "#7a8a4a", pele: "#c98d5e", cabelo: "#2a1d12", simbolo: "espiga" },
      base: { vida: 1200, atk: 106, def: 60, spd: 110, crit: 0.1, critDano: 1.55 },
      ult: {
        nome: "Onde Fores, Irei",
        desc: "Cura contínua para toda a hoste por 3 turnos.",
        acoes: [{ tipo: "regen", alvo: "todos_aliados", mult: 0.4, duracao: 3 }],
      },
      passiva: {
        nome: "Respigar",
        desc: "Cura o aliado mais ferido sempre que ataca.",
        gatilho: "ao_atacar",
        acoes: [{ tipo: "cura", alvo: "aliado_menor_vida", mult: 0.3 }],
      },
    },

    // ---------------------------------------------------------- CELESTIAIS
    {
      id: "miguel",
      nome: "Miguel",
      titulo: "Príncipe dos Exércitos",
      faccao: "celestiais",
      classe: "guerreiro",
      raridade: "lendario",
      versiculo: "Apocalipse 12:7",
      arte: { tunica: "#f2f0e2", manto: "#d8b34a", pele: "#e8c8a0", cabelo: "#f0e0a0", simbolo: "espada_flamejante" },
      base: { vida: 1900, atk: 138, def: 94, spd: 104, crit: 0.18, critDano: 1.85 },
      ult: {
        nome: "Espada Flamejante",
        desc: "Golpe celeste que atinge a frente inimiga e queima os ímpios.",
        acoes: [
          { tipo: "dano", alvo: "inimigos_frente", mult: 1.9 },
          { tipo: "dot", alvo: "inimigos_frente", estilo: "queimadura", mult: 0.3, duracao: 2 },
        ],
      },
      passiva: {
        nome: "Guarda do Trono",
        desc: "Reduz em 15% todo o dano recebido pela hoste.",
        gatilho: "passivo",
        acoes: [{ tipo: "reducao_dano_equipe", valor: 0.15 }],
      },
    },
    {
      id: "gabriel",
      nome: "Gabriel",
      titulo: "O Mensageiro",
      faccao: "celestiais",
      classe: "arauto",
      raridade: "lendario",
      versiculo: "Lucas 1:19",
      arte: { tunica: "#f5f2e8", manto: "#8ac8f0", pele: "#e8c8a0", cabelo: "#e8e0c0", simbolo: "trombeta" },
      base: { vida: 1260, atk: 140, def: 66, spd: 128, crit: 0.2, critDano: 1.75 },
      ult: {
        nome: "Anúncio",
        desc: "A trombeta soa: 60 de fé para dois aliados e purificação geral.",
        acoes: [
          { tipo: "energia", alvo: "aliados_menor_energia:2", valor: 60 },
          { tipo: "purificar", alvo: "todos_aliados" },
        ],
      },
      passiva: {
        nome: "Não Temas",
        desc: "Toda a hoste começa com 20 de fé.",
        gatilho: "inicio",
        acoes: [{ tipo: "energia", alvo: "todos_aliados", valor: 20 }],
      },
    },
    {
      id: "rafael",
      nome: "Rafael",
      titulo: "Remédio de Deus",
      faccao: "celestiais",
      classe: "sacerdote",
      raridade: "epico",
      versiculo: "Tobias 12:15",
      arte: { tunica: "#e8f2e0", manto: "#6fbf8f", pele: "#e8c8a0", cabelo: "#d8d0a0", simbolo: "peixe" },
      base: { vida: 1340, atk: 126, def: 70, spd: 114, crit: 0.14, critDano: 1.6 },
      ult: {
        nome: "Bálsamo Celeste",
        desc: "Cura poderosa em área e regeneração por 2 turnos.",
        acoes: [
          { tipo: "cura", alvo: "todos_aliados", mult: 1.15 },
          { tipo: "regen", alvo: "todos_aliados", mult: 0.25, duracao: 2 },
        ],
      },
      passiva: {
        nome: "Guia do Caminho",
        desc: "Aliados curados por ele ganham 10% de defesa por 2 turnos.",
        gatilho: "ao_curar",
        acoes: [{ tipo: "mod", alvo: "ultimo_curado", stat: "def", valor: 0.1, duracao: 2, nome: "Bálsamo" }],
      },
    },
    {
      id: "serafim",
      nome: "Serafim",
      titulo: "O Ardente",
      faccao: "celestiais",
      classe: "vidente",
      raridade: "epico",
      versiculo: "Isaías 6:2",
      arte: { tunica: "#ffd9a0", manto: "#e0602a", pele: "#f0d0a8", cabelo: "#ffefc0", simbolo: "asas" },
      base: { vida: 1120, atk: 172, def: 54, spd: 112, crit: 0.22, critDano: 1.85 },
      ult: {
        nome: "Santo, Santo, Santo",
        desc: "Três ondas de fogo sagrado sobre alvos aleatórios.",
        acoes: [{ tipo: "dano", alvo: "aleatorio_inimigos:3", mult: 1.0 }],
      },
      passiva: {
        nome: "Seis Asas",
        desc: "Ignora 20% da defesa inimiga.",
        gatilho: "passivo",
        acoes: [{ tipo: "penetracao", valor: 0.2 }],
      },
    },
    {
      id: "querubim",
      nome: "Querubim",
      titulo: "Guarda do Éden",
      faccao: "celestiais",
      classe: "guerreiro",
      raridade: "epico",
      versiculo: "Gênesis 3:24",
      arte: { tunica: "#e0e8f2", manto: "#a0b8d8", pele: "#e8c8a0", cabelo: "#f0e8c8", simbolo: "escudo" },
      base: { vida: 2000, atk: 110, def: 100, spd: 92, crit: 0.1, critDano: 1.6 },
      ult: {
        nome: "Espada que Gira",
        desc: "Provoca todos os inimigos e ergue um escudo sobre si.",
        acoes: [
          { tipo: "provocar", alvo: "todos_inimigos", duracao: 2 },
          { tipo: "escudo", alvo: "self", mult: 2.4 },
          { tipo: "dano", alvo: "todos_inimigos", mult: 0.75 },
        ],
      },
      passiva: {
        nome: "Portão do Jardim",
        desc: "Reduz em 25% o dano recebido pelos aliados da linha de trás.",
        gatilho: "passivo",
        acoes: [{ tipo: "protege_tras", valor: 0.25 }],
      },
    },

    // -------------------------------------------------------------- TREVAS
    {
      id: "jezabel",
      nome: "Jezabel",
      titulo: "A Rainha de Baal",
      faccao: "trevas",
      classe: "vidente",
      raridade: "lendario",
      versiculo: "1 Reis 21:25",
      arte: { tunica: "#6a2a5a", manto: "#2a1a2a", pele: "#d8a888", cabelo: "#1a1218", simbolo: "serpente" },
      base: { vida: 1160, atk: 178, def: 56, spd: 114, crit: 0.22, critDano: 1.9 },
      ult: {
        nome: "Maldição de Baal",
        desc: "Veneno em todos os inimigos e cura inimiga reduzida pela metade.",
        acoes: [
          { tipo: "dano", alvo: "todos_inimigos", mult: 1.0 },
          { tipo: "dot", alvo: "todos_inimigos", estilo: "veneno", mult: 0.32, duracao: 3 },
          { tipo: "mod", alvo: "todos_inimigos", stat: "cura", valor: -0.5, duracao: 3, nome: "Maldição" },
        ],
      },
      passiva: {
        nome: "Trono de Marfim",
        desc: "Rouba 10% do ataque do alvo ao atingi-lo.",
        gatilho: "ao_atacar",
        acoes: [
          { tipo: "mod", alvo: "alvo", stat: "atk", valor: -0.1, duracao: 2, nome: "Sedução" },
          { tipo: "mod", alvo: "self", stat: "atk", valor: 0.1, duracao: 2, nome: "Sedução" },
        ],
      },
    },
    {
      id: "nabucodonosor",
      nome: "Nabucodonosor",
      titulo: "O Rei da Babilônia",
      faccao: "trevas",
      classe: "guerreiro",
      raridade: "lendario",
      versiculo: "Daniel 3:1",
      arte: { tunica: "#8a6a2a", manto: "#4a2a4a", pele: "#c08858", cabelo: "#1a1218", simbolo: "coroa" },
      base: { vida: 1940, atk: 132, def: 92, spd: 96, crit: 0.16, critDano: 1.8 },
      ult: {
        nome: "Estátua de Ouro",
        desc: "Ergue-se em glória: escudo enorme, ataque aumentado e dano em área.",
        acoes: [
          { tipo: "escudo", alvo: "self", mult: 2.0 },
          { tipo: "mod", alvo: "self", stat: "atk", valor: 0.4, duracao: 3, nome: "Soberba" },
          { tipo: "dano", alvo: "todos_inimigos", mult: 0.95 },
        ],
      },
      passiva: {
        nome: "Fornalha Ardente",
        desc: "Queima quem o atinge, causando dano de retorno.",
        gatilho: "ao_receber_dano",
        acoes: [{ tipo: "reflexo", valor: 0.18 }],
      },
    },
    {
      id: "golias",
      nome: "Golias",
      titulo: "O Gigante de Gate",
      faccao: "trevas",
      classe: "guerreiro",
      raridade: "epico",
      versiculo: "1 Samuel 17:4",
      arte: { tunica: "#5a6a5a", manto: "#3a2a2a", pele: "#b08050", cabelo: "#1a1410", simbolo: "lanca" },
      base: { vida: 2050, atk: 126, def: 96, spd: 88, crit: 0.14, critDano: 1.9 },
      ult: {
        nome: "Desafio do Gigante",
        desc: "Brada contra a hoste: provoca todos e esmaga a frente.",
        acoes: [
          { tipo: "provocar", alvo: "todos_inimigos", duracao: 2 },
          { tipo: "dano", alvo: "inimigos_frente", mult: 1.75 },
        ],
      },
      passiva: {
        nome: "Couraça de Bronze",
        desc: "Recebe 20% menos dano de arqueiros e videntes.",
        gatilho: "passivo",
        acoes: [{ tipo: "resistencia_classe", classes: ["arqueiro", "vidente"], valor: 0.2 }],
      },
    },
    {
      id: "farao",
      nome: "Faraó",
      titulo: "Coração Endurecido",
      faccao: "trevas",
      classe: "arauto",
      raridade: "epico",
      versiculo: "Êxodo 8:15",
      arte: { tunica: "#d8c060", manto: "#2a4a6a", pele: "#c08858", cabelo: "#141014", simbolo: "olho" },
      base: { vida: 1240, atk: 132, def: 66, spd: 116, crit: 0.16, critDano: 1.7 },
      ult: {
        nome: "Decreto do Nilo",
        desc: "Drena 30 de fé de todos os inimigos e reduz sua velocidade.",
        acoes: [
          { tipo: "energia", alvo: "todos_inimigos", valor: -30 },
          { tipo: "mod", alvo: "todos_inimigos", stat: "spd", valor: -0.25, duracao: 3, nome: "Jugo" },
        ],
      },
      passiva: {
        nome: "Carros de Guerra",
        desc: "Aumenta em 15% o ataque dos aliados das Trevas.",
        gatilho: "inicio",
        acoes: [{ tipo: "mod_faccao", alvo: "todos_aliados", faccao: "trevas", stat: "atk", valor: 0.15, duracao: 99, nome: "Jugo" }],
      },
    },
    {
      id: "hama",
      nome: "Hamã",
      titulo: "O Conselheiro Traiçoeiro",
      faccao: "trevas",
      classe: "arqueiro",
      raridade: "raro",
      versiculo: "Ester 7:10",
      arte: { tunica: "#6a3a5a", manto: "#3a2a3a", pele: "#c08858", cabelo: "#1a1218", simbolo: "adaga" },
      base: { vida: 1020, atk: 162, def: 48, spd: 120, crit: 0.28, critDano: 1.9 },
      ult: {
        nome: "A Própria Forca",
        desc: "Executa o inimigo mais ferido com dano dobrado se ele estiver sob 35%.",
        acoes: [{ tipo: "executar", alvo: "inimigo_menor_vida", mult: 1.7, limiar: 0.35, bonus: 2.0 }],
      },
      passiva: {
        nome: "Trama Secreta",
        desc: "Ganha 12% de crítico contra alvos com menos de metade da vida.",
        gatilho: "passivo",
        acoes: [{ tipo: "crit_contra_feridos", valor: 0.12 }],
      },
    },
    {
      id: "saul",
      nome: "Saul",
      titulo: "O Rei Atormentado",
      faccao: "trevas",
      classe: "guerreiro",
      raridade: "epico",
      versiculo: "1 Samuel 16:14",
      arte: { tunica: "#5a5a6a", manto: "#7a2a2a", pele: "#c08858", cabelo: "#2a2020", simbolo: "lanca" },
      base: { vida: 1820, atk: 130, def: 84, spd: 100, crit: 0.18, critDano: 1.85 },
      ult: {
        nome: "Lança Arremessada",
        desc: "Ataca duas vezes o mesmo alvo com fúria crescente.",
        acoes: [
          { tipo: "dano", alvo: "alvo", mult: 1.2 },
          { tipo: "dano", alvo: "alvo", mult: 1.2 },
          { tipo: "mod", alvo: "self", stat: "atk", valor: 0.12, duracao: 99, nome: "Tormento" },
        ],
      },
      passiva: {
        nome: "Espírito Mau",
        desc: "Abaixo de 50% de vida ganha 25% de velocidade e 20% de ataque.",
        gatilho: "vida_baixa",
        acoes: [
          { tipo: "mod", alvo: "self", stat: "spd", valor: 0.25, duracao: 99, nome: "Tormento" },
          { tipo: "mod", alvo: "self", stat: "atk", valor: 0.2, duracao: 99, nome: "Tormento" },
        ],
      },
    },

    // ----------------------------------------------------- FIÉIS (comuns)
    {
      id: "adao",
      nome: "Adão",
      titulo: "O Primeiro Homem",
      faccao: "patriarcas",
      classe: "guerreiro",
      raridade: "comum",
      versiculo: "Gênesis 2:7",
      arte: { tunica: "#8a7a5a", manto: "#4a6a3a", pele: "#c98d5e", cabelo: "#3a2a1a", simbolo: "espiga" },
      base: { vida: 1580, atk: 96, def: 78, spd: 92, crit: 0.1, critDano: 1.55 },
      ult: {
        nome: "Pó da Terra",
        desc: "Golpe pesado que devolve parte do dano em vida.",
        acoes: [{ tipo: "roubo", alvo: "alvo", mult: 1.5, roubo: 0.4 }],
      },
      passiva: {
        nome: "Sopro de Vida",
        desc: "Recupera 5% da vida máxima a cada turno.",
        gatilho: "cada_turno",
        acoes: [{ tipo: "cura", alvo: "self", mult: 0, pctVida: 0.05 }],
      },
    },
    {
      id: "eva",
      nome: "Eva",
      titulo: "Mãe dos Viventes",
      faccao: "patriarcas",
      classe: "sacerdote",
      raridade: "comum",
      versiculo: "Gênesis 3:20",
      arte: { tunica: "#c8a8b8", manto: "#6a8a5a", pele: "#d8a070", cabelo: "#3a2418", simbolo: "espiga" },
      base: { vida: 1180, atk: 104, def: 58, spd: 112, crit: 0.1, critDano: 1.55 },
      ult: {
        nome: "Fruto da Vida",
        desc: "Cura a hoste e deixa regeneração por 2 turnos.",
        acoes: [
          { tipo: "cura", alvo: "todos_aliados", mult: 0.7 },
          { tipo: "regen", alvo: "todos_aliados", mult: 0.18, duracao: 2 },
        ],
      },
      passiva: {
        nome: "Auxiliadora",
        desc: "Concede 10% de defesa à hoste no início da batalha.",
        gatilho: "inicio",
        acoes: [{ tipo: "mod", alvo: "todos_aliados", stat: "def", valor: 0.1, duracao: 99, nome: "Abrigo" }],
      },
    },
    {
      id: "calebe",
      nome: "Calebe",
      titulo: "O Espião Fiel",
      faccao: "juizes",
      classe: "guerreiro",
      raridade: "comum",
      versiculo: "Números 14:24",
      arte: { tunica: "#7a8a5a", manto: "#4a5a3a", pele: "#b87a4a", cabelo: "#2a1d12", simbolo: "escudo" },
      base: { vida: 1600, atk: 100, def: 80, spd: 94, crit: 0.12, critDano: 1.6 },
      ult: {
        nome: "Dai-me Esta Montanha",
        desc: "Investida contra a frente inimiga que reforça a própria defesa.",
        acoes: [
          { tipo: "dano", alvo: "inimigo_frente", mult: 1.5 },
          { tipo: "mod", alvo: "self", stat: "def", valor: 0.25, duracao: 3, nome: "Herança" },
        ],
      },
      passiva: {
        nome: "Outro Espírito",
        desc: "Ganha 10% de ataque a cada turno seu.",
        gatilho: "cada_turno",
        acoes: [{ tipo: "mod", alvo: "self", stat: "atk", valor: 0.1, duracao: 99, nome: "Ânimo" }],
      },
    },
    {
      id: "miria",
      nome: "Miriã",
      titulo: "A Profetisa do Pandeiro",
      faccao: "profetas",
      classe: "arauto",
      raridade: "comum",
      versiculo: "Êxodo 15:20",
      arte: { tunica: "#d8c8a0", manto: "#8a5a7a", pele: "#c98d5e", cabelo: "#2a1d12", simbolo: "harpa" },
      base: { vida: 1140, atk: 112, def: 56, spd: 116, crit: 0.14, critDano: 1.6 },
      ult: {
        nome: "Cântico do Mar",
        desc: "Acelera a hoste e devolve fé a todos.",
        acoes: [
          { tipo: "mod", alvo: "todos_aliados", stat: "spd", valor: 0.18, duracao: 3, nome: "Cântico" },
          { tipo: "energia", alvo: "todos_aliados", valor: 12 },
        ],
      },
      passiva: {
        nome: "Pandeiro",
        desc: "Ao atacar, concede 6 de fé ao aliado com menos fé.",
        gatilho: "ao_atacar",
        acoes: [{ tipo: "energia", alvo: "aliado_menor_energia", valor: 6 }],
      },
    },
    {
      id: "jonatas",
      nome: "Jônatas",
      titulo: "O Amigo do Ungido",
      faccao: "realeza",
      classe: "arqueiro",
      raridade: "comum",
      versiculo: "1 Samuel 18:4",
      arte: { tunica: "#9ab0c8", manto: "#3a5a7a", pele: "#c98d5e", cabelo: "#5a3a1a", simbolo: "arco" },
      base: { vida: 960, atk: 144, def: 46, spd: 118, crit: 0.24, critDano: 1.7 },
      ult: {
        nome: "Flechas do Pacto",
        desc: "Duas flechas rápidas contra o inimigo mais ferido.",
        acoes: [
          { tipo: "dano", alvo: "inimigo_menor_vida", mult: 0.95 },
          { tipo: "dano", alvo: "inimigo_menor_vida", mult: 0.95 },
        ],
      },
      passiva: {
        nome: "Aliança de Irmãos",
        desc: "Ao derrotar um inimigo, recupera 15 de fé.",
        gatilho: "ao_matar",
        acoes: [{ tipo: "energia", alvo: "self", valor: 15 }],
      },
    },
    {
      id: "obadias",
      nome: "Obadias",
      titulo: "O Mordomo Fiel",
      faccao: "profetas",
      classe: "sacerdote",
      raridade: "comum",
      versiculo: "1 Reis 18:4",
      arte: { tunica: "#c0b090", manto: "#5a6a7a", pele: "#c98d5e", cabelo: "#4a3a2a", simbolo: "jarro" },
      base: { vida: 1220, atk: 102, def: 62, spd: 106, crit: 0.1, critDano: 1.55 },
      ult: {
        nome: "Esconderijo na Caverna",
        desc: "Ergue escudo sobre toda a hoste.",
        acoes: [{ tipo: "escudo", alvo: "todos_aliados", mult: 0.8 }],
      },
      passiva: {
        nome: "Pão e Água",
        desc: "Cura o aliado mais ferido a cada turno.",
        gatilho: "cada_turno",
        acoes: [{ tipo: "cura", alvo: "aliado_menor_vida", mult: 0.25 }],
      },
    },
  ];

  const porId = {};
  HEROIS.forEach((h) => (porId[h.id] = h));

  Jogo.Herois = HEROIS;
  Jogo.heroiPorId = (id) => porId[id];
})(typeof window !== "undefined" ? window : globalThis);
